<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GeneralSettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('general_settings')->delete();
        
        \DB::table('general_settings')->insert(array (
            0 => 
            array (
                'id' => 4,
                'name' => 'web_facebook_link',
                'display_name' => 'Facebook',
                'value' => 'https://facebook.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            1 => 
            array (
                'id' => 5,
                'name' => 'web_twitter_link',
                'display_name' => 'Twitter',
                'value' => 'https://Twitter.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            2 => 
            array (
                'id' => 6,
                'name' => 'logo',
                'display_name' => 'Logo',
                'value' => '/images/settings/logo.png',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'image',
                'page' => NULL,
                'created_at' => '2024-06-21 17:14:39',
                'updated_at' => '2024-06-21 17:14:39',
            ),
            3 => 
            array (
                'id' => 11,
                'name' => 'home_section1_heading',
                'display_name' => 'Section 1 Heading',
                'value' => 'Members',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            4 => 
            array (
                'id' => 12,
                'name' => 'home_section1_icon',
                'display_name' => 'Section 1 Icon',
                'value' => 'bi bi-person-vcard-fill',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            5 => 
            array (
                'id' => 13,
                'name' => 'home_section1_value',
                'display_name' => 'Section 1 Value',
                'value' => '100',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            6 => 
            array (
                'id' => 17,
                'name' => 'home_section2_heading',
                'display_name' => 'Section 2 Heading',
                'value' => 'Teachers',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            7 => 
            array (
                'id' => 18,
                'name' => 'home_section2_icon',
                'display_name' => 'Section 2 Icon',
                'value' => 'bi bi-person-heart',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            8 => 
            array (
                'id' => 19,
                'name' => 'home_section2_value',
                'display_name' => 'Section 2 Value',
                'value' => '77',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            9 => 
            array (
                'id' => 24,
                'name' => 'home_section3_heading',
                'display_name' => 'Section 3 Heading',
                'value' => 'Appointments Booked',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-08-25 21:36:16',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            10 => 
            array (
                'id' => 25,
                'name' => 'home_section3_icon',
                'display_name' => 'Section 3 Icon',
                'value' => 'bi bi-calendar-heart-fill',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            11 => 
            array (
                'id' => 26,
                'name' => 'home_section3_value',
                'display_name' => 'Section 3 Value',
                'value' => '97',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            12 => 
            array (
                'id' => 27,
                'name' => 'home_section4_heading',
                'display_name' => 'Section 4 Heading',
                'value' => 'Academies',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            13 => 
            array (
                'id' => 28,
                'name' => 'home_section4_icon',
                'display_name' => 'Section 4 Icon',
                'value' => 'bi bi-buildings-fill',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            14 => 
            array (
                'id' => 29,
                'name' => 'home_section4_value',
                'display_name' => 'Section 4 Value',
                'value' => '84',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            15 => 
            array (
                'id' => 30,
                'name' => 'web_youtube_link',
                'display_name' => 'Youtube',
                'value' => 'https://youtube.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            16 => 
            array (
                'id' => 31,
                'name' => 'web_linkedin_link',
                'display_name' => 'Linkedin',
                'value' => 'https://linkedin.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            17 => 
            array (
                'id' => 32,
                'name' => 'web_whatsapp_link',
                'display_name' => 'Whatsapp',
                'value' => 'https://whatsapp.com/asd',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            18 => 
            array (
                'id' => 33,
                'name' => 'footer_crisis_support_statement',
                'display_name' => 'Footer Crisis Support Statement',
                'value' => '<b>Don\'t use this site if:</b> You are in a crisis or if any other person may be in danger.',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'textarea',
                'page' => 'website_footer',
                'created_at' => '2023-01-18 23:17:32',
                'updated_at' => '2023-01-18 18:16:43',
            ),
            19 => 
            array (
                'id' => 34,
                'name' => 'web_instagram_link',
                'display_name' => 'Instagram',
                'value' => 'https://instagram.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            20 => 
            array (
                'id' => 35,
                'name' => 'web_snapchat_link',
                'display_name' => 'Snapchat',
                'value' => 'https://snapchat.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            21 => 
            array (
                'id' => 36,
                'name' => 'web_pinterest_link',
                'display_name' => 'Pinterest',
                'value' => 'https://pinterest.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            22 => 
            array (
                'id' => 37,
                'name' => 'web_tiktok_link',
                'display_name' => 'TikTok',
                'value' => 'https://tiktok.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'website_social_links',
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            23 => 
            array (
                'id' => 38,
                'name' => 'home_section5_heading',
                'display_name' => 'Section 5 Heading',
                'value' => 'Events',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            24 => 
            array (
                'id' => 39,
                'name' => 'home_section5_icon',
                'display_name' => 'Section 5 Icon',
                'value' => 'bi bi-balloon-heart-fill',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            25 => 
            array (
                'id' => 40,
                'name' => 'home_section5_value',
                'display_name' => 'Section 5 Value',
                'value' => '100',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'number',
                'page' => 'home_page_statistics',
                'created_at' => '2023-02-15 22:08:43',
                'updated_at' => '2023-02-15 21:08:43',
            ),
            26 => 
            array (
                'id' => 41,
                'name' => 'agora_app_id',
                'display_name' => 'AGORA APP ID',
                'value' => 'ee3d69d271fb409e93347069503f4803',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            27 => 
            array (
                'id' => 43,
                'name' => 'agora_app_certificate',
                'display_name' => 'AGORA APP CERTIFICATE',
                'value' => '3f8f4c99dc2748db88a286fbbfc6b1c7',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            28 => 
            array (
                'id' => 44,
                'name' => 'pusher_beams_instance_id',
                'display_name' => 'PUSHER BEAMS INSTANCE ID',
                'value' => '41feeeff-28a1-4aca-8e1f-367d292906ec',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            29 => 
            array (
                'id' => 45,
                'name' => 'pusher_beams_secret_key',
                'display_name' => 'PUSHER BEAMS SECRET KEY',
                'value' => '0F3C4B8299756A807C1A9D293B5E18CAEE0D5EBB0F258E091AED8BBBAF8D64DF',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            30 => 
            array (
                'id' => 46,
                'name' => 'pusher_app_id',
                'display_name' => 'PUSHER APP ID',
                'value' => '1665700',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            31 => 
            array (
                'id' => 47,
                'name' => 'pusher_app_key',
                'display_name' => 'PUSHER APP KEY',
                'value' => '9d8e7b5c8ce69b2c07af',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            32 => 
            array (
                'id' => 48,
                'name' => 'pusher_app_secret',
                'display_name' => 'PUSHER APP SECRET',
                'value' => '3249dca6b5e76fc1a98d',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            33 => 
            array (
                'id' => 49,
                'name' => 'pusher_app_cluster',
                'display_name' => 'PUSHER APP CLUSTER',
                'value' => 'ap2',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            34 => 
            array (
                'id' => 50,
                'name' => 'stripe_key',
                'display_name' => 'STRIPE KEY',
                'value' => 'pk_test_51MjnELHTAHWwyrB6HqKFzapBSOjSEAF9dKUz7JAI9vPTQHtsGsFJrhm151hdiVQWyvsvtq1CpkSMEmAUjC0pgbEl00P1BNfXvD',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'payment_method_settings',
                'created_at' => '2024-05-02 18:02:15',
                'updated_at' => '2024-05-02 18:02:15',
            ),
            35 => 
            array (
                'id' => 51,
                'name' => 'stripe_secret',
                'display_name' => 'STRIPE SECRET',
                'value' => 'sk_test_51MjnELHTAHWwyrB6o5FbJewlU1QQeOvwfJoCBfnlf20KzNGa7JVyxIWhYIb84Ohl8kUxvGDuzOkCSo3rFj9Ne85l00FvdXN2ti',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'payment_method_settings',
                'created_at' => '2024-05-02 18:02:15',
                'updated_at' => '2024-05-02 18:02:15',
            ),
            36 => 
            array (
                'id' => 52,
                'name' => 'google_client_id',
                'display_name' => 'GOOGLE CLIENT ID',
                'value' => '1006558285844-81r1j9n23vovqg9uebrae8tcg79v7t4b.apps.googleusercontent.com',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            37 => 
            array (
                'id' => 53,
                'name' => 'google_client_secret',
                'display_name' => 'GOOGLE CLIENT SECRET',
                'value' => 'Uru8dkoJjf3ey401DG8gLaq5',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            38 => 
            array (
                'id' => 54,
                'name' => 'facebook_client_id',
                'display_name' => 'FACEBOOK CLIENT ID',
                'value' => '887082349379468',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            39 => 
            array (
                'id' => 55,
                'name' => 'facebook_client_secret',
                'display_name' => 'FACEBOOK CLIENT SECRET',
                'value' => '163a1cc69bd8a9706700e816544b1429',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2023-02-16 02:08:43',
                'updated_at' => '2023-02-16 01:08:43',
            ),
            40 => 
            array (
                'id' => 56,
                'name' => 'contact_us_email',
                'display_name' => 'Contact Us Receiving Email',
                'value' => 'info@hexathemes.com',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'email',
                'page' => NULL,
                'created_at' => '2024-06-21 17:14:39',
                'updated_at' => '2024-06-21 17:14:39',
            ),
            41 => 
            array (
                'id' => 57,
                'name' => 'site_title',
                'display_name' => 'Site Title',
                'value' => 'Tutor-Hub',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => NULL,
                'created_at' => '2024-06-21 17:14:39',
                'updated_at' => '2024-06-21 17:14:39',
            ),
            42 => 
            array (
                'id' => 59,
                'name' => 'enable_wallet_system',
                'display_name' => 'Enable Wallet System',
                'value' => '1',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => NULL,
                'created_at' => '2024-06-21 17:14:39',
                'updated_at' => '2024-06-21 17:14:39',
            ),
            43 => 
            array (
                'id' => 60,
                'name' => 'commission_type',
                'display_name' => 'Select Commission Type',
                'value' => 'subscription_base',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'select_option',
                'page' => NULL,
                'created_at' => '2024-06-21 17:14:39',
                'updated_at' => '2024-06-21 17:14:39',
            ),
            44 => 
            array (
                'id' => 61,
                'name' => 'dark_logo',
                'display_name' => 'Dark Logo',
                'value' => '/images/settings/dark_logo.png',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'image',
                'page' => NULL,
                'created_at' => '2024-06-21 12:03:37',
                'updated_at' => '2024-06-21 12:03:37',
            ),
            45 => 
            array (
                'id' => 62,
                'name' => 'mail_encryption',
                'display_name' => 'Mail Encryption',
                'value' => 'null',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2024-05-21 17:49:28',
                'updated_at' => '2024-05-14 16:59:45',
            ),
            46 => 
            array (
                'id' => 63,
                'name' => 'mail_password',
                'display_name' => 'Mail Password',
                'value' => '275f0deee12cf5',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2024-05-21 17:49:28',
                'updated_at' => '2024-05-14 16:59:45',
            ),
            47 => 
            array (
                'id' => 64,
                'name' => 'mail_username',
                'display_name' => 'Mail Username',
                'value' => '5e61912602edf9',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2024-05-21 17:51:09',
                'updated_at' => '2024-05-14 16:59:45',
            ),
            48 => 
            array (
                'id' => 65,
                'name' => 'mail_port',
                'display_name' => 'Mail Port',
                'value' => '587',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2024-05-21 17:51:09',
                'updated_at' => '2024-05-14 16:59:45',
            ),
            49 => 
            array (
                'id' => 66,
                'name' => 'mail_host',
                'display_name' => 'Mail Host',
                'value' => 'sandbox.smtp.mailtrap.io',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2024-05-21 17:51:09',
                'updated_at' => '2024-05-14 16:59:45',
            ),
            50 => 
            array (
                'id' => 67,
                'name' => 'mail_driver',
                'display_name' => 'Mail Driver',
                'value' => 'smtp',
                'is_specific' => 1,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => 'configurations',
                'created_at' => '2024-05-21 17:51:09',
                'updated_at' => '2024-05-14 16:59:45',
            ),
            51 => 
            array (
                'id' => 68,
                'name' => 'auto_approve_academy_service',
                'display_name' => 'Auto Approve Academy Service',
                'value' => '1',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => '',
                'created_at' => '2024-05-14 17:49:16',
                'updated_at' => '2023-02-16 02:08:43',
            ),
            52 => 
            array (
                'id' => 69,
                'name' => 'auto_approve_teacher_service',
                'display_name' => 'Auto Approve Teacher Service',
                'value' => '1',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => '',
                'created_at' => '2024-05-14 17:49:16',
                'updated_at' => '2023-02-16 02:08:43',
            ),
            53 => 
            array (
                'id' => 70,
                'name' => 'app_version',
                'display_name' => 'App Version',
                'value' => '1.0.2',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'text',
                'page' => NULL,
                'created_at' => '2024-04-29 18:28:43',
                'updated_at' => '2024-04-29 18:28:43',
            ),
            54 => 
            array (
                'id' => 71,
                'name' => 'is_auto_approve',
                'display_name' => 'Auto Approve Users',
                'value' => '1',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => NULL,
                'created_at' => '2024-12-18 11:42:40',
                'updated_at' => '2024-12-18 11:42:40',
            ),
            55 => 
            array (
                'id' => 72,
                'name' => 'is_ai_chatbot_enable',
                'display_name' => 'Is AI chatBot Enable',
                'value' => '1',
                'is_specific' => 0,
                'is_multilang' => 0,
                'type' => 'boolean_selection',
                'page' => NULL,
                'created_at' => '2024-12-18 11:42:40',
                'updated_at' => '2024-12-18 11:42:40',
            ),
        ));
        
        
    }
}