<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('students')->delete();
        
        \DB::table('students')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 2,
                'user_name' => 'jack',
                'country_id' => 167,
                'state_id' => 3176,
                'city_id' => 85437,
                'first_name' => 'Mary',
                'last_name' => 'Jennifer',
                'description' => 'Jack Testing Student',
                'address_line_1' => 'D Ground People Colony',
                'address_line_2' => 'Faisalabad',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/652fcc3d5fab9.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-01 16:54:49',
                'updated_at' => '2024-04-01 13:46:54',
                'deleted_at' => '2024-04-01 13:46:54',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 4,
                'user_name' => 'sir_john',
                'country_id' => 19,
                'state_id' => 766,
                'city_id' => 8541,
                'first_name' => 'John',
                'last_name' => 'James',
                'description' => NULL,
                'address_line_1' => '123 Main Street
Anytown, USA
12345',
                'address_line_2' => '123 Main Street
Anytown, USA
12345',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/652fc895e6093.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-03 15:51:33',
                'updated_at' => '2024-04-01 13:42:29',
                'deleted_at' => '2024-04-01 13:42:29',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 18,
                'user_name' => 'James_Daniel',
                'country_id' => 19,
                'state_id' => 766,
                'city_id' => 8541,
                'first_name' => 'James',
                'last_name' => 'Daniel',
                'description' => 'asd asds',
                'address_line_1' => '123 Main Street
Anytown, USA
12345',
                'address_line_2' => '123 Main Street
Anytown, USA
12345',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/652fcb5adc5a7.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-09 09:16:12',
                'updated_at' => '2024-04-01 13:42:25',
                'deleted_at' => '2024-04-01 13:42:25',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 19,
                'user_name' => 'abc12',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Tonny',
                'last_name' => 'Jaw',
                'description' => 'Hi there! I\'m Tonny, and I\'m passionate about [mention a few of your interests]. I\'m always up for trying new foods, discovering great music, and exploring new places. When I\'m not indulging in my hobbies, you can find me at work or spending quality time with family and friends. Feel free to connect with me; I love meeting new people and making meaningful connections.',
                'address_line_1' => '80880',
                'address_line_2' => 'Adress in Uk Street 1',
                'zip_code' => 'Adress in Uk',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'icon' => NULL,
                'image' => '/images/profile_images/6530f2797834d.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-09 11:58:55',
                'updated_at' => '2024-04-01 13:42:48',
                'deleted_at' => '2024-04-01 13:42:48',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 17,
                'user_name' => 'Michael_Clark',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Michael',
                'last_name' => 'Clark',
                'description' => 'Isabella Carrington is a dynamic and results-driven attorney with a passion for justice and a strong commitment to her clients\' well-being. With a wealth of legal experience and a reputation for strategic thinking, Isabella has established herself as a trusted advocate known for her tenacity and dedication.

Education:

J.D. (Juris Doctor), Belleview Law School
B.A. in Political Science, University of Belleview',
                'address_line_1' => 'house 325',
                'address_line_2' => NULL,
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/teachers/64ccd745aaa0b.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-22 18:00:55',
                'updated_at' => '2024-04-01 13:42:37',
                'deleted_at' => '2024-04-01 13:42:37',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 16,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Sophia',
                'last_name' => 'Lancaster',
                'description' => 'Sophia Lancaster is a skilled and compassionate attorney who is dedicated to advocating for her clients\' rights and ensuring access to justice. With a diverse legal background and a deep commitment to serving her community, Sophia has earned a reputation as a reliable and empathetic advocate.

Education:

J.D. (Juris Doctor), Summitville Law School
B.A. in Sociology, University of Summitville
Areas of Expertise:

Sophia specializes in family law, offering comprehensive legal support in matters such as divorce, child custody, spousal support, and adoption. Her extensive experience in mediation and negotiation enables her to guide her clients through challenging family situations while minimizing conflict. Sophia also provides legal assistance in estate planning, offering clients peace of mind for the future.',
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/teachers/64ccd745aaa0b.png',
                'cover_image' => NULL,
                'created_at' => '2023-08-25 13:58:58',
                'updated_at' => '2024-04-01 13:42:43',
                'deleted_at' => '2024-04-01 13:42:43',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 20,
                'user_name' => 'Elizabeth_Jhon',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Elizabeth',
                'last_name' => 'Jhon',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/teachers/64ccd745aaa0b.png',
                'cover_image' => NULL,
                'created_at' => '2023-09-27 10:57:37',
                'updated_at' => '2024-04-01 13:42:13',
                'deleted_at' => '2024-04-01 13:42:13',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 22,
                'user_name' => 'John_Morgan',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'John',
                'last_name' => 'Morgan',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/teachers/64ccd745aaa0b.png',
                'cover_image' => NULL,
                'created_at' => '2023-09-27 15:52:55',
                'updated_at' => '2024-04-01 13:42:07',
                'deleted_at' => '2024-04-01 13:42:07',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 40,
                'user_name' => 'sir_faizan',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Faizan',
                'last_name' => 'Fazal',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-10-26 19:54:30',
                'updated_at' => '2023-10-26 20:02:45',
                'deleted_at' => '2023-10-26 20:02:45',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 42,
                'user_name' => 'sir_fazal',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Faizan',
                'last_name' => 'Fazal',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-10-26 20:12:05',
                'updated_at' => '2023-10-26 20:12:59',
                'deleted_at' => '2023-10-26 20:12:59',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 3,
                'user_name' => 'sir_dave',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'john',
                'last_name' => 'dave',
                'description' => 'hello i am a student hello',
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/students/6542467632fc0.png',
                'cover_image' => NULL,
                'created_at' => '2023-11-01 17:37:10',
                'updated_at' => '2023-11-01 17:38:48',
                'deleted_at' => '2023-11-01 17:38:48',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 45,
                'user_name' => 'lily_Gabriel',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Lily',
                'last_name' => 'Gabriel',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 02:19:00',
                'updated_at' => '2024-04-01 13:48:13',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 46,
                'user_name' => 'Harper_Orbes',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Harper',
                'last_name' => 'Orbes',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => '220102',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/students/663e2d14726e0.png',
                'cover_image' => NULL,
                'created_at' => '2023-11-23 04:51:14',
                'updated_at' => '2024-05-10 19:20:04',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 48,
                'user_name' => 'dd',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'dd',
                'last_name' => 'dd',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 10:12:31',
                'updated_at' => '2024-04-01 13:09:18',
                'deleted_at' => '2024-04-01 13:09:18',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 49,
                'user_name' => 'Carter_subhy',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Carter',
                'last_name' => 'subhy',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 13:48:49',
                'updated_at' => '2024-04-01 13:46:46',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 53,
                'user_name' => 'Sebastian_sina',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Sebastian',
                'last_name' => 'sina',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => 'nw',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 16:13:45',
                'updated_at' => '2024-04-01 13:49:50',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 54,
                'user_name' => 'Jackson_sinasi',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Jackson',
                'last_name' => 'sinasi',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 16:15:35',
                'updated_at' => '2024-04-01 13:50:18',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 55,
                'user_name' => 'testetes',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'test',
                'last_name' => 'test',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 18:20:32',
                'updated_at' => '2024-04-01 13:10:56',
                'deleted_at' => '2024-04-01 13:10:56',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 56,
                'user_name' => 'Amelia_Jack',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Amelia',
                'last_name' => 'Jack',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-23 18:27:46',
                'updated_at' => '2024-04-01 13:40:01',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 57,
                'user_name' => 'seeker',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'ddw',
                'last_name' => 'User',
                'description' => 'sweet',
                'address_line_1' => '12344',
                'address_line_2' => NULL,
                'zip_code' => 'london',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/files/profile_images/1705387746scaled_image_picker3190099173755574307.jpg',
                'cover_image' => NULL,
                'created_at' => '2023-11-23 18:30:50',
                'updated_at' => '2024-04-01 13:09:58',
                'deleted_at' => '2024-04-01 13:09:58',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 58,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Consultant',
                'last_name' => 'Teacher',
                'description' => '',
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 1,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-11-24 19:57:39',
                'updated_at' => '2024-04-01 13:09:12',
                'deleted_at' => '2024-04-01 13:09:12',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 61,
                'user_name' => 'Paul_Nardo',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Paul',
                'last_name' => 'Nardo',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-02 14:07:38',
                'updated_at' => '2024-04-01 13:45:29',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 63,
                'user_name' => 'Henry_Daniel',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Henry',
                'last_name' => 'Daniel',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/students/663f4194c0c42.png',
                'cover_image' => NULL,
                'created_at' => '2023-12-03 23:15:32',
                'updated_at' => '2024-06-13 18:10:52',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 64,
                'user_name' => 'Ethna_doe',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Ethan',
                'last_name' => 'doe',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/students/663e28d326e19.png',
                'cover_image' => NULL,
                'created_at' => '2023-12-06 17:11:50',
                'updated_at' => '2024-06-06 15:06:03',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 65,
                'user_name' => 'Oliver_Sarith',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Oliver',
                'last_name' => 'Sarith',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => '2345654',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-07 18:04:05',
                'updated_at' => '2024-04-01 13:44:54',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 66,
                'user_name' => 'Owen_roy',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Owen',
                'last_name' => 'roy',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-09 13:11:15',
                'updated_at' => '2024-04-01 13:49:11',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 67,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'odind',
                'last_name' => 'odjdj',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-11 17:22:48',
                'updated_at' => '2024-04-01 13:11:33',
                'deleted_at' => '2024-04-01 13:11:33',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 68,
                'user_name' => 'fg',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'dagi',
                'last_name' => 'abea',
                'description' => 'fh',
                'address_line_1' => '100',
                'address_line_2' => NULL,
                'zip_code' => 'ch',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/files/profile_images/1703170511scaled_1000193631.jpg',
                'cover_image' => NULL,
                'created_at' => '2023-12-14 00:11:38',
                'updated_at' => '2024-04-01 13:08:54',
                'deleted_at' => '2024-04-01 13:08:54',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 70,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'n',
                'last_name' => 'n',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-18 16:36:11',
                'updated_at' => '2024-04-01 13:10:14',
                'deleted_at' => '2024-04-01 13:10:14',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 73,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'dagi abea',
                'last_name' => 'dagi abea',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-22 17:35:16',
                'updated_at' => '2024-04-01 13:09:01',
                'deleted_at' => '2024-04-01 13:09:01',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 76,
                'user_name' => 'Aurora_Layla',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Aurora',
                'last_name' => 'Layla',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-23 06:24:13',
                'updated_at' => '2024-04-01 13:51:35',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 77,
                'user_name' => 'Matthew_wade',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Matthew',
                'last_name' => 'wade',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-24 12:59:22',
                'updated_at' => '2024-04-01 13:48:44',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 79,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'nhat',
                'last_name' => 'nem',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2023-12-25 13:46:08',
                'updated_at' => '2024-04-01 13:10:45',
                'deleted_at' => '2024-04-01 13:10:45',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 83,
                'user_name' => 'Jacob_Bui',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Jacob',
                'last_name' => 'Bui',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-03 13:44:06',
                'updated_at' => '2024-04-01 13:31:34',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 84,
                'user_name' => 'hssj',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'nhat',
                'last_name' => 'nhat',
                'description' => 'hhjj',
                'address_line_1' => 'hhhh',
                'address_line_2' => NULL,
                'zip_code' => 'hhhh',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/files/profile_images/1704683155scaled_928e145a-4407-4699-8788-c09bf78b8cdc5485286519308985743.jpg',
                'cover_image' => NULL,
                'created_at' => '2024-01-04 12:54:23',
                'updated_at' => '2024-04-01 13:10:34',
                'deleted_at' => '2024-04-01 13:10:34',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 86,
                'user_name' => 'Lucas_alaimo',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Lucas',
                'last_name' => 'alaimo',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-06 15:46:34',
                'updated_at' => '2024-04-01 13:37:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 87,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'test',
                'last_name' => 'luat',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-01-08 12:13:41',
                'updated_at' => '2024-04-01 13:11:05',
                'deleted_at' => '2024-04-01 13:11:05',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 89,
                'user_name' => 'Alexander_haque',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Alexander',
                'last_name' => 'haque',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/students/6661a70b41577.png',
                'cover_image' => NULL,
                'created_at' => '2024-01-09 04:19:11',
                'updated_at' => '2024-06-06 17:09:47',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 96,
                'user_name' => 'Chloe_foster',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Chloe',
                'last_name' => 'foster',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/students/663e26958fae8.png',
                'cover_image' => NULL,
                'created_at' => '2024-01-31 10:16:26',
                'updated_at' => '2024-06-20 15:19:57',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 99,
                'user_name' => 'monoali',
                'country_id' => 167,
                'state_id' => 3176,
                'city_id' => 85437,
                'first_name' => 'mono',
                'last_name' => 'Ali',
                'description' => 'sasasasa',
                'address_line_1' => 'Punjab',
                'address_line_2' => 'Pakistan',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/6650766a16a41.png',
                'cover_image' => NULL,
                'created_at' => '2024-05-24 15:40:45',
                'updated_at' => '2024-05-24 16:13:46',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 101,
                'user_name' => 'david',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'David',
                'last_name' => 'Denny',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-05-25 11:38:10',
                'updated_at' => '2024-05-25 11:38:10',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 102,
                'user_name' => 'bilalnaeem5',
                'country_id' => 1,
                'state_id' => 3871,
                'city_id' => 72,
                'first_name' => 'Bilal',
                'last_name' => 'Naeem',
                'description' => '12312312',
                'address_line_1' => 'helo',
                'address_line_2' => 'test 3',
                'zip_code' => '1234123',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66583bcb25b41.png',
                'cover_image' => '/images/cover_images/66583bcb25fe3.png',
                'created_at' => '2024-05-30 13:33:27',
                'updated_at' => '2024-05-30 13:41:47',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 103,
                'user_name' => 'mahadbaig',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'mahad',
                'last_name' => 'baig',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-06-03 13:06:16',
                'updated_at' => '2024-06-14 15:21:49',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 105,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Naveed',
                'last_name' => 'Mughal',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-06-06 13:37:40',
                'updated_at' => '2024-06-06 13:37:40',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 17,
                'user_name' => 'hellocarrington',
                'country_id' => 1,
                'state_id' => 1,
                'city_id' => 1,
                'first_name' => 'hello',
                'last_name' => 'Carrington',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque commodo augue vel dui cursus, non luctus urna congue. Vestibulum ut ultricies tortor. Sed eu libero nec ex tristique fringilla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In vitae magna eu justo lacinia feugiat. Duis auctor vulputate quam, sit amet tincidunt ipsum consequat ut. Curabitur eu risus vitae neque posuere cursus ut ut quam. Integer tempor risus non dolor luctus, eget accumsan nisl eleifend. Fusce venenatis nulla non lacus tincidunt, ut sollicitudin libero mollis',
                'address_line_1' => '12345566',
                'address_line_2' => '1234556',
                'zip_code' => '38000',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/images/profile_images/66697ac505fc5.png',
                'cover_image' => NULL,
                'created_at' => '2024-06-06 14:44:34',
                'updated_at' => '2024-06-26 13:53:30',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 108,
                'user_name' => NULL,
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'Rick',
                'last_name' => 'Jones',
                'description' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'zip_code' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => NULL,
                'cover_image' => NULL,
                'created_at' => '2024-06-07 16:28:33',
                'updated_at' => '2024-06-07 16:28:33',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 109,
                'user_name' => 'mono',
                'country_id' => NULL,
                'state_id' => NULL,
                'city_id' => NULL,
                'first_name' => 'mono',
                'last_name' => 'ali',
                'description' => 'hello world',
                'address_line_1' => 'ahhshdhd',
                'address_line_2' => NULL,
                'zip_code' => '3800',
                'is_active' => 1,
                'is_featured' => 0,
                'is_online' => 0,
                'icon' => NULL,
                'image' => '/files/profile_images/1717766494scaled_4830021a-89b5-476c-b694-19e235f8050c8602650057524946107.jpg',
                'cover_image' => NULL,
                'created_at' => '2024-06-07 18:07:52',
                'updated_at' => '2024-06-07 18:21:34',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}