<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TeacherReviewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('teacher_reviews')->delete();
        
        \DB::table('teacher_reviews')->insert(array (
            0 => 
            array (
                'id' => 1,
                'teacher_id' => 15,
                'student_id' => 4,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'teacher_id' => 14,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'teacher_id' => 13,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'teacher_id' => 12,
                'student_id' => 4,
                'rating' => 4.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'teacher_id' => 11,
                'student_id' => 8,
                'rating' => 4.5,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'teacher_id' => 15,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'teacher_id' => 15,
                'student_id' => 8,
                'rating' => 4.5,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'teacher_id' => 14,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-09-21 11:06:06',
                'updated_at' => '2023-09-21 11:06:06',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'teacher_id' => 14,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-13 20:10:20',
                'updated_at' => '2023-10-13 20:10:20',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'teacher_id' => 1,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'teacher_id' => 1,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'teacher_id' => 1,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'teacher_id' => 2,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'teacher_id' => 2,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'teacher_id' => 2,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'teacher_id' => 3,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'teacher_id' => 3,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'teacher_id' => 3,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'teacher_id' => 8,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'teacher_id' => 8,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'teacher_id' => 8,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'teacher_id' => 9,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'teacher_id' => 9,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'teacher_id' => 9,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'teacher_id' => 11,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'teacher_id' => 11,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'teacher_id' => 11,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'teacher_id' => 12,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'teacher_id' => 12,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'teacher_id' => 12,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'teacher_id' => 13,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'teacher_id' => 13,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'teacher_id' => 13,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'teacher_id' => 15,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'teacher_id' => 15,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'teacher_id' => 15,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'teacher_id' => 21,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'teacher_id' => 21,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'teacher_id' => 21,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'teacher_id' => 22,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'teacher_id' => 22,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'teacher_id' => 22,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'teacher_id' => 23,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'teacher_id' => 23,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'teacher_id' => 23,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'teacher_id' => 24,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'teacher_id' => 24,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'teacher_id' => 24,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'teacher_id' => 25,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'teacher_id' => 25,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'teacher_id' => 25,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'teacher_id' => 26,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'teacher_id' => 26,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'teacher_id' => 26,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'teacher_id' => 27,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'teacher_id' => 27,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'teacher_id' => 27,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'teacher_id' => 28,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'teacher_id' => 28,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'teacher_id' => 28,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'teacher_id' => 29,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'teacher_id' => 29,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'teacher_id' => 29,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'teacher_id' => 30,
                'student_id' => 3,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Great Work and communication thanks very helpful',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'teacher_id' => 30,
                'student_id' => 2,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'I was completely impressed with their professionalism and student service.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'teacher_id' => 30,
                'student_id' => 1,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Highly recommended – it\'s a must-have for everyone',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2023-10-17 16:43:22',
                'updated_at' => '2023-10-17 16:43:22',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'teacher_id' => 33,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Mason Williams is a teacher who truly embodies the essence of education as a transformative force. His passion for teaching radiates in every interaction, making learning not just a task but an enriching experience. What sets Mason apart is his ability to tailor his teaching methods to suit the unique needs of each student, ensuring that no one is left behind.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-10 18:50:43',
                'updated_at' => '2024-05-10 18:50:43',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'teacher_id' => 33,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Mason William is an exceptional teacher whose passion for education is evident in every lesson. As a dedicated educator, he goes above and beyond to ensure his students not only grasp the material but also develop a genuine love for learning. His teaching style is dynamic, incorporating innovative methods to engage students and make complex concepts easily understandable. Mason fosters a supportive classroom environment where students feel encouraged to ask questions and explore new ideas.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-10 18:59:40',
                'updated_at' => '2024-05-10 18:59:40',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'teacher_id' => 27,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'i am satisfied with that teacher',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-10 23:16:40',
                'updated_at' => '2024-05-10 23:16:40',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'teacher_id' => 33,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Mason William is an exceptional teacher who brings enthusiasm and expertise to his classroom. His teaching style fosters engagement and critical thinking, making learning enjoyable for students. With a knack for explaining complex concepts in simple terms, he ensures that every student grasps the material.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:01:39',
                'updated_at' => '2024-05-11 15:01:39',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'teacher_id' => 30,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Peter Adams is an exceptional teacher who brings enthusiasm and expertise to his classroom. His teaching style fosters engagement and critical thinking, making learning enjoyable for students. With a knack for explaining complex concepts in simple terms, he ensures that every student grasps the material.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:02:48',
                'updated_at' => '2024-05-11 15:02:48',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'teacher_id' => 30,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Peter Adam is a phenomenal teacher, epitomizing dedication and expertise. His passion for education radiates through his engaging teaching style, making complex subjects easily understandable. His unwavering support fosters a conducive learning environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:03:53',
                'updated_at' => '2024-05-11 15:03:53',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'teacher_id' => 30,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Peter Adam embodies the epitome of an exceptional educator. His passion for teaching shines through in every lesson, captivating students with his engaging style and deep knowledge. With a blend of enthusiasm and expertise, he fosters an environment where learning flourishes.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:05:08',
                'updated_at' => '2024-05-11 15:05:08',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'teacher_id' => 26,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'James Cooper embodies the epitome of an exceptional educator. His passion for teaching shines through in every lesson, captivating students with his engaging style and deep knowledge. With a blend of enthusiasm and expertise, he fosters an environment where learning flourishes.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:06:00',
                'updated_at' => '2024-05-11 15:06:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'teacher_id' => 26,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'James Cooper is an exceptional educator whose passion for teaching shines through in every lesson. With a wealth of knowledge and a genuine commitment to his students\' success, he creates a supportive learning environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:06:54',
                'updated_at' => '2024-05-11 15:06:54',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'teacher_id' => 26,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'James Cooper is an exemplary educator whose passion for teaching shines through in every lesson. With a dynamic teaching style, he fosters an engaging learning environment where students thrive. His depth of knowledge and dedication to his craft make him a standout teacher.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:07:57',
                'updated_at' => '2024-05-11 15:07:57',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'teacher_id' => 25,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'David Thompason is an exemplary educator who epitomizes dedication and passion in his teaching. His approach is both engaging and insightful, fostering a dynamic learning environment where students thrive. With a profound understanding of his subject matter, he effortlessly imparts knowledge while nurturing critical thinking skills.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:09:14',
                'updated_at' => '2024-05-11 15:09:14',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'teacher_id' => 25,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'David Thompason embodies the quintessential educator, blending expertise with passion in his teaching. With a profound dedication to his craft, he cultivates an enriching learning environment where students thrive. His dynamic approach fosters engagement and encourages critical thinking, leaving a lasting impact on all who have the privilege of being in his classroom.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:10:22',
                'updated_at' => '2024-05-11 15:10:22',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'teacher_id' => 25,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'David Thompson teaching style is commendable, blending expertise with empathy. His passion for the subject shines through, engaging students and fostering a positive learning environment. With clear explanations and interactive methods,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:11:18',
                'updated_at' => '2024-05-11 15:11:18',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'teacher_id' => 24,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Noah Benjamin teaching style is commendable, blending expertise with empathy. His passion for the subject shines through, engaging students and fostering a positive learning environment. With clear explanations and interactive methods,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:12:08',
                'updated_at' => '2024-05-11 15:12:08',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'teacher_id' => 24,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Noah Benjamin embodies the epitome of an exceptional educator. His passion for teaching radiates in every lesson, captivating students with engaging content and fostering a dynamic learning environment. With a profound commitment to student success, Mason\'s dedication goes beyond the classroom, leaving a lasting impact on his pupils.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:13:15',
                'updated_at' => '2024-05-11 15:13:15',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'teacher_id' => 24,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Noah Benjamin is an exemplary educator whose passion for teaching shines through in every lesson. With his engaging teaching style and depth of knowledge, he fosters an environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:14:36',
                'updated_at' => '2024-05-11 15:14:36',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'teacher_id' => 23,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Brown David is  exemplary educator whose passion for teaching shines through in every lesson. With his engaging teaching style and depth of knowledge, he fosters an environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:15:36',
                'updated_at' => '2024-05-11 15:15:36',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'teacher_id' => 23,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Brown David is an exemplary educator who embodies passion and dedication in teaching. His dynamic approach captivates students, fostering an engaging learning environment. With a wealth of knowledge and innovative teaching methods, he ensures every student comprehends complex concepts.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:16:57',
                'updated_at' => '2024-05-11 15:16:57',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'teacher_id' => 23,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Brown David embodies the epitome of an exceptional educator. His teaching style seamlessly blends expertise with empathy, fostering an environment where students thrive. With clear communication and a genuine passion for his subject, he ignites curiosity and inspires lifelong learning.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:18:00',
                'updated_at' => '2024-05-11 15:18:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'teacher_id' => 22,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sarah Mia embodies the epitome of an exceptional educator. His teaching style seamlessly blends expertise with empathy, fostering an environment where students thrive. With clear communication and a genuine passion for his subject, he ignites curiosity and inspires lifelong learning.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:21:48',
                'updated_at' => '2024-05-11 15:21:48',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'teacher_id' => 22,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sarah Mia is an exceptional teacher who excels in both knowledge and approachability. His teaching style is engaging, making complex subjects accessible to all students. With a keen understanding of individual learning needs, he fosters a supportive classroom environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:22:51',
                'updated_at' => '2024-05-11 15:22:51',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'teacher_id' => 22,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sarah mia is an exemplary educator whose passion for teaching shines brightly in every lesson. His approachability and dedication foster an engaging learning environment where students thrive. With a knack for simplifying complex concepts and a genuine interest in student success,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:23:54',
                'updated_at' => '2024-05-11 15:23:54',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'teacher_id' => 21,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Liam Daniel is an exemplary educator whose passion for teaching shines brightly in every lesson. His approachability and dedication foster an engaging learning environment where students thrive. With a knack for simplifying complex concepts and a genuine interest in student success,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:26:59',
                'updated_at' => '2024-05-11 15:26:59',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'teacher_id' => 21,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Liam Daniel is an exemplary educator whose passion for teaching shines through in every lesson. With his extensive knowledge and engaging teaching style, he captivates students\' attention and fosters a love for learning.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:28:13',
                'updated_at' => '2024-05-11 15:28:13',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'teacher_id' => 21,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Liam Daniel is an exceptional educator who embodies dedication and passion in his teaching. With a wealth of knowledge and a nurturing demeanor, he fosters an environment where students thrive. His engaging teaching style and genuine care for his students make learning both enjoyable and meaningful.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:29:14',
                'updated_at' => '2024-05-11 15:29:14',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'teacher_id' => 15,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Ava Carrington is an exceptional educator who embodies dedication and passion in his teaching. With a wealth of knowledge and a nurturing demeanor, he fosters an environment where students thrive. His engaging teaching style and genuine care for his students make learning both enjoyable and meaningful.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:30:01',
                'updated_at' => '2024-05-11 15:30:01',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'teacher_id' => 15,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Ava Carrington is an exemplary educator whose passion for teaching shines through in every lesson. With a profound understanding of his subject matter, he engages students effortlessly, fostering a dynamic learning environment.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:30:55',
                'updated_at' => '2024-05-11 15:30:55',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'teacher_id' => 15,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Ava Carrington teaching is exemplary! His passion for education shines through every lesson, making learning engaging and enjoyable. With his extensive knowledge and effective communication skills, he fosters a supportive classroom environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:31:50',
                'updated_at' => '2024-05-11 15:31:50',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'teacher_id' => 14,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Emma Lancaster teaching is exemplary! His passion for education shines through every lesson, making learning engaging and enjoyable. With his extensive knowledge and effective communication skills, he fosters a supportive classroom environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:32:51',
                'updated_at' => '2024-05-11 15:32:51',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'teacher_id' => 14,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Emma Lancaster embodies the quintessential educator. With a deep passion for his subject matter and a knack for engaging students, he fosters an environment where learning thrives. His approachable demeanor and commitment to student success make him a standout teacher.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:33:37',
                'updated_at' => '2024-05-11 15:33:37',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'teacher_id' => 14,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Emma lancaster is an exceptional educator who brings passion and expertise to the classroom. With a dynamic teaching style and a genuine dedication to his students\' success, he fosters a stimulating learning environment.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:35:06',
                'updated_at' => '2024-05-11 15:35:06',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'teacher_id' => 13,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Elijah James is an exceptional educator who brings passion and expertise to the classroom. With a dynamic teaching style and a genuine dedication to his students\' success, he fosters a stimulating learning environment.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:38:03',
                'updated_at' => '2024-05-11 15:38:03',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'teacher_id' => 13,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Elijah James is an exceptional educator whose passion for teaching radiates in every lesson. With a profound understanding of his subject matter and a knack for engaging students, he fosters a dynamic learning environment where curiosity thrives.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:38:53',
                'updated_at' => '2024-05-11 15:38:53',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'teacher_id' => 13,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Elijah James is an exceptional educator who truly embodies the essence of teaching. With a wealth of knowledge and a passion for imparting it, he engages students in meaningful ways, fostering a love for learning.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:39:48',
                'updated_at' => '2024-05-11 15:39:48',
                'deleted_at' => NULL,
            ),
        ));
        \DB::table('teacher_reviews')->insert(array (
            0 => 
            array (
                'id' => 101,
                'teacher_id' => 12,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Evelyn Victoria is an exceptional educator who truly embodies the essence of teaching. With a wealth of knowledge and a passion for imparting it, he engages students in meaningful ways, fostering a love for learning.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:40:30',
                'updated_at' => '2024-05-11 15:40:30',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 102,
                'teacher_id' => 12,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Evelyn Victoria is an exceptional teacher whose passion for education shines through in every lesson. His ability to engage students and make complex concepts understandable is truly remarkable. With a nurturing demeanor, he creates a supportive learning environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:42:22',
                'updated_at' => '2024-05-11 15:42:22',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 103,
                'teacher_id' => 12,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Evelyn Victoria is a remarkable educator who exemplifies passion and dedication in his teaching. His innovative methods engage students and foster a dynamic learning environment. With a profound knowledge of his subject matter and a genuine commitment to student success, Mason creates an enriching experience for all.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:44:47',
                'updated_at' => '2024-05-11 15:44:47',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 104,
                'teacher_id' => 12,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Evelyn Victoria is a remarkable educator who exemplifies passion and dedication in his teaching. His innovative methods engage students and foster a dynamic learning environment. With a profound knowledge of his subject matter and a genuine commitment to student success, Mason creates an enriching experience for all.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:44:47',
                'updated_at' => '2024-05-11 15:44:47',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 105,
                'teacher_id' => 11,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Logan Bradford is a remarkable educator who exemplifies passion and dedication in his teaching. His innovative methods engage students and foster a dynamic learning environment. With a profound knowledge of his subject matter and a genuine commitment to student success, Mason creates an enriching experience for all.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:45:36',
                'updated_at' => '2024-05-11 15:45:36',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 106,
                'teacher_id' => 11,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Logan bradford is an exceptional educator, embodying the true essence of teaching. With profound knowledge and a passion for imparting wisdom, he fosters an engaging learning environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:46:38',
                'updated_at' => '2024-05-11 15:46:38',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 107,
                'teacher_id' => 11,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Logan Bradford embodies the epitome of an exceptional educator. His teaching prowess extends beyond mere impartation of knowledge; it\'s a transformative journey for his students. With unwavering dedication, he fosters an environment of curiosity and critical thinking.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:47:41',
                'updated_at' => '2024-05-11 15:47:41',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 108,
                'teacher_id' => 8,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Lucas Bannet embodies the epitome of an exceptional educator. His teaching prowess extends beyond mere impartation of knowledge; it\'s a transformative journey for his students. With unwavering dedication, he fosters an environment of curiosity and critical thinking.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:48:35',
                'updated_at' => '2024-05-11 15:48:35',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 109,
                'teacher_id' => 8,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Lucas Bennett embodies the epitome of a dedicated educator. His passion for teaching radiates through every lesson, captivating students\' attention and fostering an environment of learning and growth.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:51:12',
                'updated_at' => '2024-05-11 15:51:12',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 110,
                'teacher_id' => 8,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Lucas Bannett embodies the epitome of an exceptional educator. With a profound dedication to his craft, he transforms classrooms into dynamic learning environments. His engaging teaching style captivates students, fostering a deep understanding of complex subjects. Beyond knowledge dissemination, Mason cultivates critical thinking and empowers his students to excel.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:52:09',
                'updated_at' => '2024-05-11 15:52:09',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 111,
                'teacher_id' => 2,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Benjamin Mark embodies the epitome of an exceptional educator. With a profound dedication to his craft, he transforms classrooms into dynamic learning environments. His engaging teaching style captivates students, fostering a deep understanding of complex subjects. Beyond knowledge dissemination, Mason cultivates critical thinking and empowers his students to excel.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 15:53:29',
                'updated_at' => '2024-05-11 15:53:29',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 112,
                'teacher_id' => 2,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Benjamin mark is an exceptional teacher whose dedication shines through in his work. With his engaging teaching style and deep subject knowledge, he creates an enriching learning environment for his students.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 16:54:21',
                'updated_at' => '2024-05-11 16:54:21',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 113,
                'teacher_id' => 2,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Benjamin Mark is an exceptional teacher, embodying dedication and expertise in his craft. His passion for education shines through his engaging teaching style, fostering a dynamic learning environment. With a keen understanding of his subject matter, he effortlessly connects with students, igniting curiosity and facilitating deep understanding.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 16:55:25',
                'updated_at' => '2024-05-11 16:55:25',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 114,
                'teacher_id' => 2,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Benjamin Mark is an exceptional teacher, embodying dedication and expertise in his craft. His passion for education shines through his engaging teaching style, fostering a dynamic learning environment. With a keen understanding of his subject matter, he effortlessly connects with students, igniting curiosity and facilitating deep understanding.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 16:55:25',
                'updated_at' => '2024-05-11 16:55:25',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 115,
                'teacher_id' => 1,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sophia John is an exceptional teacher, embodying dedication and expertise in his craft. His passion for education shines through his engaging teaching style, fostering a dynamic learning environment. With a keen understanding of his subject matter, he effortlessly connects with students, igniting curiosity and facilitating deep understanding.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 16:58:13',
                'updated_at' => '2024-05-11 16:58:13',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 116,
                'teacher_id' => 1,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sophia john is an exceptional teacher who brings passion and expertise to his role. His dedication to student success is evident in his engaging teaching style and commitment to fostering a positive learning environment.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 16:59:11',
                'updated_at' => '2024-05-11 16:59:11',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 117,
                'teacher_id' => 1,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sophia john is an exemplary educator, demonstrating a profound commitment to his students\' growth. With a dynamic teaching style, he effortlessly engages his class, fostering a stimulating learning environment.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 16:59:59',
                'updated_at' => '2024-05-11 16:59:59',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 118,
                'teacher_id' => 31,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'John james is an exemplary teacher whose dedication to his craft is evident in every lesson. His passion for imparting knowledge is inspiring, fostering an engaging and supportive learning environment. With clear explanations and creative teaching methods, he ensures every student grasps concepts thoroughly.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:40:54',
                'updated_at' => '2024-05-11 18:40:54',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 119,
                'teacher_id' => 31,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'John James is an exceptional teacher whose dedication to his craft shines through in every lesson. His passion for teaching is contagious, fostering an engaging and supportive learning environment. With a deep knowledge of his subject matter and innovative teaching methods,',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:41:45',
                'updated_at' => '2024-05-11 18:41:45',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 120,
                'teacher_id' => 31,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'John James is a remarkable educator whose passion for teaching shines through in every lesson. His ability to engage students and foster a dynamic learning environment is truly commendable. With his dedication to excellence and innovative teaching methods, Mason ensures that every student not only understands the material but also develops a genuine enthusiasm for learning.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:42:42',
                'updated_at' => '2024-05-11 18:42:42',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 121,
                'teacher_id' => 27,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sophia Martinez is a remarkable educator whose passion for teaching shines through in every lesson. His ability to engage students and foster a dynamic learning environment is truly commendable. With his dedication to excellence and innovative teaching methods, Mason ensures that every student not only understands the material but also develops a genuine enthusiasm for learning.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:44:04',
                'updated_at' => '2024-05-11 18:44:04',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 122,
                'teacher_id' => 27,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Sophia Martinez is an exceptional educator whose passion for teaching shines through in every lesson. With a profound knowledge of his subject matter and a genuine dedication to his students\' success, he fosters an engaging and supportive learning environment. His innovative teaching methods and ability to connect with students make him a standout teacher.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:44:52',
                'updated_at' => '2024-05-11 18:44:52',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 123,
                'teacher_id' => 9,
                'student_id' => 23,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Harper Lee is an exceptional educator whose passion for teaching shines through in every lesson. With a profound knowledge of his subject matter and a genuine dedication to his students\' success, he fosters an engaging and supportive learning environment. His innovative teaching methods and ability to connect with students make him a standout teacher.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:46:05',
                'updated_at' => '2024-05-11 18:46:05',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 124,
                'teacher_id' => 9,
                'student_id' => 24,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Harper Lee teaching prowess is exemplary. His dedication to his craft shines through in every lesson. With a knack for engaging his students, he fosters an environment where learning flourishes effortlessly. His depth of knowledge coupled with his approachable demeanor creates an enriching educational experience.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:46:59',
                'updated_at' => '2024-05-11 18:46:59',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 125,
                'teacher_id' => 9,
                'student_id' => 39,
                'rating' => 5.0,
                'experience' => 5.0,
                'communication' => 5.0,
                'service' => 5.0,
                'comment' => 'Harper Lee is an exceptional educator, embodying the essence of passion and dedication in teaching. His approach is both insightful and engaging, fostering a dynamic learning environment where students thrive.',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-11 18:47:51',
                'updated_at' => '2024-05-11 18:47:51',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 126,
                'teacher_id' => 33,
                'student_id' => 39,
                'rating' => 1.0,
                'experience' => 1.0,
                'communication' => 1.0,
                'service' => 1.0,
                'comment' => 'ok',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-31 15:55:16',
                'updated_at' => '2024-05-31 15:55:16',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 127,
                'teacher_id' => 27,
                'student_id' => 39,
                'rating' => 1.0,
                'experience' => 1.0,
                'communication' => 1.0,
                'service' => 1.0,
                'comment' => 'just ok',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-31 15:56:19',
                'updated_at' => '2024-05-31 15:56:19',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 128,
                'teacher_id' => 33,
                'student_id' => 39,
                'rating' => 1.0,
                'experience' => 1.0,
                'communication' => 1.0,
                'service' => 1.0,
                'comment' => 'okooko',
                'is_active' => 1,
                'is_approved' => 0,
                'is_featured' => 0,
                'created_at' => '2024-05-31 15:58:08',
                'updated_at' => '2024-05-31 15:58:08',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}